name: Build and Deploy redis database to Production

on:
  workflow_dispatch:
    inputs:
      JENKINS_PRE_URL:
        type: string
        required: true
        description: Provide the Jenkins URL to trigger the job

env:
  JENKINS_JOB: 'redis-database'
  JENKINS_TIMEOUT: 3600

jobs:
  Jenkins-CICD-Trigger:
    runs-on: robot-shop-runner
    steps:
    - name: Trigger jenkins job
      run: |
        response=$(curl -i -X POST -u ${{ secrets.JENKINS_PRE_USERNAME }}:${{ secrets.JENKINS_PRE_PASSWORD }} "${{ inputs.JENKINS_PRE_URL }}/job/Robot%20Shop/job/${{ env.JENKINS_JOB }}/build?token=${{ secrets.JENKINS_PRE_TOKEN }}")
        
        echo "response: $response"

        queue_location=$(echo "$response" | grep -i 'Location:' | awk '{print $2}' | tr -d '\r')

        while true; do
          buildnumber=$(curl -X GET -u ${{ secrets.JENKINS_PRE_USERNAME }}:${{ secrets.JENKINS_PRE_PASSWORD }} "${queue_location}api/json" | jq '.executable.number')
          if [[ $buildnumber != "null" ]]; then
            echo "Build Started with Build number: $buildnumber"
            echo "buildnumber=$buildnumber" >> $GITHUB_ENV
            break
          else
            echo "Build still in queue"
            sleep 30
          fi
        done
    
    - name: Check Jenkins build status
      run: |
        start=$EPOCHSECONDS
        while true; do
          response=$(curl -s -u ${{ secrets.JENKINS_PRE_USERNAME }}:${{ secrets.JENKINS_PRE_PASSWORD }} "${{ inputs.JENKINS_PRE_URL }}/job/Robot%20Shop/job/${{ env.JENKINS_JOB }}/${{ env.buildnumber }}/api/json")

          build_result=$(echo $response | jq -r '.result')
          echo "The build result is: $build_result"

          if [[ $build_result == "FAILURE" ]]; then
            echo "The build has Failed ❌"
            exit 1
          elif [[ $build_result == "SUCCESS" ]]; then
            echo "The build has Succeeded ✅"
            sleep 30
            break
          else
            echo "Waiting to complete..."
          fi

          if (( EPOCHSECONDS-start > ${{ env.JENKINS_TIMEOUT }} )); then
            echo "Jenkins job has timed out!!!"
            break
          fi
        done